export const stages = [
  {
    id: "beginner",
    title: "Beginner",
    icon: "🌱",
    description: "Core syntax and essential flags",
    lessons: [
      { id: "b1", title: "Basic syntax: grep PATTERN FILE", example: 'grep "error" log.txt' },
      { id: "b2", title: "Case-insensitive search: -i", example: 'grep -i "Error" log.txt' },
      { id: "b3", title: "Show line numbers: -n", example: 'grep -n "TODO" *.js' },
      { id: "b4", title: "Count matches: -c", example: 'grep -c "fail" results.txt' },
      { id: "b5", title: "Recursive search: -r / -R", example: 'grep -r "config" ./src' },
    ],
    resources: [
      { title: "GNU grep manual", url: "https://www.gnu.org/software/grep/manual/grep.html", type: "docs" },
      { title: "Linux man page (online)", url: "https://man7.org/linux/man-pages/man1/grep.1.html", type: "docs" },
      { title: "grep crash course (YouTube)", url: "https://www.youtube.com/results?search_query=grep+linux+tutorial+beginner", type: "video" },
    ],
    challenges: [
      { id: "bc1", title: "Find all lines containing 'error' (case-insensitive) in a log file", difficulty: "easy" },
      { id: "bc2", title: "List line numbers of every TODO comment in a JS file", difficulty: "easy" },
      { id: "bc3", title: "Count how many times 'null' appears in a JSON file", difficulty: "easy" },
      { id: "bc4", title: "Recursively find all files under ./src that reference 'config'", difficulty: "medium" },
      { id: "bc5", title: "Search for 'warning' OR 'error' using two separate grep invocations piped with ||", difficulty: "medium" },
    ],
  },
  {
    id: "intermediate",
    title: "Intermediate",
    icon: "🔧",
    description: "Inversion, context lines, and output control",
    lessons: [
      { id: "i1", title: "Invert match: -v", example: 'grep -v "^#" config.txt' },
      { id: "i2", title: "Whole-word match: -w", example: 'grep -w "log" app.js' },
      { id: "i3", title: "Print only the match: -o", example: 'grep -o "[0-9]\\+" data.txt' },
      { id: "i4", title: "Context lines: -A N, -B N, -C N", example: 'grep -C 3 "exception" app.log' },
      { id: "i5", title: "List matching filenames only: -l / -L", example: 'grep -rl "TODO" ./src' },
      { id: "i6", title: "Multiple patterns: -e", example: 'grep -e "foo" -e "bar" file.txt' },
      { id: "i7", title: "Fixed string, no regex: -F", example: 'grep -F "1.2.3" package.json' },
    ],
    resources: [
      { title: "grep flags cheatsheet (ss64)", url: "https://ss64.com/bash/grep.html", type: "docs" },
      { title: "Intermediate grep examples (Linux Handbook)", url: "https://linuxhandbook.com/grep-command-examples/", type: "article" },
      { title: "Regex basics for grep (RegexOne)", url: "https://regexone.com/", type: "interactive" },
    ],
    challenges: [
      { id: "ic1", title: "Strip all comment lines (starting with #) from a config file using -v", difficulty: "easy" },
      { id: "ic2", title: "Find the word 'log' but not 'login' or 'logger' using -w", difficulty: "medium" },
      { id: "ic3", title: "Extract all IP addresses from a log file using -o and a pattern", difficulty: "medium" },
      { id: "ic4", title: "Show 5 lines of context around every 'panic' entry in a Go log", difficulty: "medium" },
      { id: "ic5", title: "List only filenames (not lines) containing 'import React' under ./src", difficulty: "medium" },
      { id: "ic6", title: "Search for the literal string '${var}' without triggering regex expansion", difficulty: "hard" },
    ],
  },
  {
    id: "advanced",
    title: "Advanced",
    icon: "⚡",
    description: "Extended regex, POSIX classes, and safe pipelines",
    lessons: [
      { id: "a1", title: "Extended regex mode: -E (ERE)", example: 'grep -E "^(foo|bar)" file.txt' },
      { id: "a2", title: "POSIX character classes: [:alpha:], [:digit:], …", example: 'grep -E "[[:digit:]]{3}-[[:digit:]]{4}" phones.txt' },
      { id: "a3", title: "Anchors and alternation in ERE", example: 'grep -E "(error|warn|crit):" syslog' },
      { id: "a4", title: "Null-separated filenames: -Z (safe with xargs)", example: 'grep -rlZ "TODO" . | xargs -0 wc -l' },
      { id: "a5", title: "Binary file handling: -a / --text", example: 'grep -a "magic" binary.bin' },
      { id: "a6", title: "Suppress permission errors: -s", example: 'grep -rs "secret" /etc' },
      { id: "a7", title: "Load patterns from a file: -f", example: 'grep -f blocklist.txt access.log' },
    ],
    resources: [
      { title: "POSIX ERE syntax reference", url: "https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html", type: "docs" },
      { title: "grep + xargs patterns (Unix StackExchange)", url: "https://unix.stackexchange.com/questions/tagged/grep+xargs", type: "community" },
      { title: "The Art of Command Line", url: "https://github.com/jlevy/the-art-of-command-line", type: "article" },
    ],
    challenges: [
      { id: "ac1", title: "Match lines starting with either 'GET' or 'POST' using ERE alternation", difficulty: "medium" },
      { id: "ac2", title: "Extract all email addresses from a file using POSIX character classes", difficulty: "hard" },
      { id: "ac3", title: "Find all TODO / FIXME / HACK comments recursively and count each type", difficulty: "hard" },
      { id: "ac4", title: "Use grep -Z and xargs -0 to safely rename files containing a pattern", difficulty: "hard" },
      { id: "ac5", title: "Load a blocklist.txt and filter matching lines out of access.log", difficulty: "medium" },
      { id: "ac6", title: "Search inside .gz log files without decompressing them first (zgrep)", difficulty: "hard" },
    ],
  },
  {
    id: "expert",
    title: "Expert",
    icon: "🏆",
    description: "PCRE, performance tuning, and toolchain integration",
    lessons: [
      { id: "e1", title: "Perl-compatible regex: -P (PCRE)", example: 'grep -P "(?<=id=)\\d+" html.txt' },
      { id: "e2", title: "Lookahead and lookbehind in PCRE", example: 'grep -P "foo(?=bar)" file.txt' },
      { id: "e3", title: "Performance tricks: -F, LC_ALL=C", example: 'LC_ALL=C grep -F "string" huge.log' },
      { id: "e4", title: "Integration with find using -exec", example: 'find . -name "*.py" -exec grep -l "import os" {} +' },
      { id: "e5", title: "Scripting with exit codes: 0 found, 1 not found, 2 error", example: 'grep -q "error" log.txt && echo "found"' },
      { id: "e6", title: "ripgrep (rg) as a modern drop-in alternative", example: 'rg --type py "def main"' },
    ],
    resources: [
      { title: "PCRE syntax reference (pcre.org)", url: "https://www.pcre.org/original/doc/html/pcresyntax.html", type: "docs" },
      { title: "ripgrep user guide", url: "https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md", type: "docs" },
      { title: "How grep works internally (Russ Cox)", url: "https://swtch.com/~rsc/regexp/regexp1.html", type: "article" },
      { title: "Learn GNU grep and ripgrep (free book)", url: "https://learnbyexample.github.io/learn_gnugrep_ripgrep/", type: "book" },
    ],
    challenges: [
      { id: "ec1", title: "Use a PCRE lookbehind to extract all values after 'id=' in an HTML file", difficulty: "hard" },
      { id: "ec2", title: "Benchmark grep -F vs grep -E on a large file and explain the speed difference", difficulty: "hard" },
      { id: "ec3", title: "Write a shell script that exits non-zero when any TODO remains in ./src", difficulty: "hard" },
      { id: "ec4", title: "Replace a recursive grep with ripgrep and note what changes", difficulty: "medium" },
      { id: "ec5", title: "Chain find + grep + sed to rename an import path across an entire project", difficulty: "expert" },
    ],
  },
];
